---
title: "Stock Market Index Model"
author: "Akira Sasaki"
date: "26/04/2017"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
library(knitr)
opts_chunk$set(message = FALSE, error = TRUE, fig.pos = 'H', tidy.opts=list(width.cutoff=65), tidy=TRUE, fig.path='figs/', cache.path='cache/graphics-', 
           fig.align='center', fig.width = 5, fig.height = 4, fig.show = 'hold',
           cache = TRUE, par = TRUE)
```

```{r setting, include=FALSE, echo=FALSE}
library(foreign) #read foreign file objects
install.packages("dplyr", repos = "https://cran.rstudio.com/")
library(dplyr) #manipulate data
install.packages("ggplot2", repos = "https://cran.rstudio.com/")
library(ggplot2) #plot results
install.packages("psych", repos = "https://cran.rstudio.com/")
library(psych) #create summary statistics
library(plyr) #tools for splitting, qpplying and combining data
library(data.table)
require(haven)
library(lubridate)
install.packages("repmis")
library(repmis)
library(data.table)
library(magrittr)
DAX <- fread('https://chart.finance.yahoo.com/table.csv?s=%5EGDAXI&a=10&b=26&c=1990&d=3&e=27&f=2017&g=d&ignore=.csv')
CDAX <- read.csv("~/hertie-election-forecasting (Akira)/^CDAXX.csv")
CDAX$Date <- ymd(as.character(CDAX$Date))
CDAX$X3M_before <- ymd(as.character(CDAX$X3M_before))
CDAX$X6M_before <- ymd(as.character(CDAX$X6M_before))
CDAX$X9M_before <- ymd(as.character(CDAX$X9M_before))
CDAX$X12_before <- ymd(as.character(CDAX$X12_before))
StockHist <- read.csv("~/hertie-election-forecasting (Akira)/Tab__01_Aktienindex__Dividendenrendite__Performance-Index__Index_der_Lebenshaltungskosten__Realer_Pe.csv")
GfK <- read.csv('~/hertie-election-forecasting (Akira)/GfK.csv')
GFE_Kayser <- read_dta('~/hertie-election-forecasting (Akira)/BundestagForecastReplicationData.dta')
GFE <- read_dta('~/hertie-election-forecasting (Akira)/data/ger_nat.dta')
election_dates <- load('~/hertie-election-forecasting/data/election_dates.RData')
GDP <- read.csv('~/hertie-election-forecasting (Akira)/CLVMNACSCAB1GQDE.csv')
GDP$Date <- ymd(as.character(GDP$DATE))
GFE$Date <- election_date
GFE$Date <- ymd(as.character(GFE$Date))
GFE_Kayser$Date <- as.Date(GFE_Kayser$date, "%d.%m.%Y")
DAX_GfK <- merge(DAX, GfK, by = "Date")
GFE.con <- merge(CDAX, GFE_Kayser, by = "Date")

```

```{r plot CDAX_GfK, include=TRUE, echo=TRUE}
par(mar = c(5,5,2,5))
with(DAX_GfK, plot(as.Date(Date), Close, type="l", col="red3",
xlab="Year", ylab=expression(DAX)),
ylim=c(0,1200))
par(new = T)
with(DAX_GfK , plot(as.Date(Date), Actual, type="l", axes=F, col="blue3", xlab="Year", ylab=NA, cex=1.2))
axis(side = 4)
mtext(side = 4, line = 3, 'GfK Consumer Confidence')
legend("topleft",
legend=c(expression(CDAX), "GfK Consumer Confidence"),
lty=1:1, cex=0.75, col=c("red3", "blue3"))
ccfvalues <- ccf(DAX_GfK$Close, DAX_GfK$Actual)
ccfvalues
perception <- lm(Actual ~ Close, DAX_GfK)
summary(perception)

#xts package
#zoo
```

```{r plot CDAX_GDP, include=TRUE, echo=TRUE}
install.packages("xts")
library(xts)
CDAX2 <- CDAX[endpoints(CDAX$Date, on = "months"), ]
locs <- tapply(X=CDAX2$Date, FUN=min, INDEX=format(CDAX2$Date, '%Y%m'))
t(t(locs))
at = CDAX2$Date %in% locs
at = at & format(CDAX2$Date, '%m') %in% c('03', '06', '09', '12')
CDAX3 <- CDAX2[which(at == TRUE),]
CDAX3 <- subset(CDAX3, Date > as.Date("1991-01-01"))
CDAX3$stock_gr <- as.numeric(CDAX3$Close)/lag(as.numeric(CDAX3$Close,1)-1)*100
par(mar = c(5,5,2,5))
with(CDAX3, plot(as.Date(Date), stock_gr, type="l", col="red3", 
xlab="Year", ylab= "CDAX quarterly growth (%)"), 
ylim=c(0,1200))
par(new = T)
with(GDP, plot(as.Date(Date), GDP_growth, type="l", axes=F, col="blue3", xlab="Year", ylab=NA, cex=1.2))
axis(side = 4)
mtext(side = 4, line = 3, 'GDP quarterly growth (%)')
legend("topleft",
legend=c("DAX quarterly growth (%)", "GDP quarterly growth (%)"),
lty=1:1, cex=0.50, col=c("red3", "blue3"))
ccfvalues3 <- ccf(stock_GDP$stock_gr, stock_GDP$GDP_growth, na.action = na.pass)
ccfvalues3
```

```{r plot DAX & GfK, include=TRUE, echo=TRUE}
par(mar = c(5,5,2,5))
with(DAX_GfK, (as.Date(Date), Close, type="l", col="red3",
xlab="Year", ylab=expression(DAX)),
ylim=c(0,1200))
par(new = T)
with(eco.in, plot(as.Date(Date), Actual, type="l", axes=F, col="blue3", xlab="Year", ylab=NA, cex=1.2))
axis(side = 4)
mtext(side = 4, line = 3, 'GfK Consumer Confidence')
legend("topleft",
legend=c(expression(DAX), "GfK Consumer Confidence"),
lty=1:1, cex=0.75, col=c("red3", "blue3"))
ccfvalues2 <- ccf(DAX_GfK$Close, DAX_GfK$Actual)
ccfvalues2
```

```{r consolidated, include=TRUE, echo=TRUE}

```

```{r regression, include=TRUE, echo=TRUE}
m <- lm(outgovshare ~ three_month + prelecshare + pid + logterms, GFE_Kayser)
m1 <- lm(outgovshare ~ six_month + prelecshare + pid + logterms, GFE_Kayser)
m2 <- lm(outgovshare ~ nine_month + prelecshare + pid + logterms, GFE_Kayser)
m3 <- lm(outgovshare ~ twelve_month + prelecshare + pid + logterms, GFE_Kayser)
summary(m)
```


```{r}
rm(list = ls())
```

